#!/bin/sh
# Auto Setup GeeLas OS - MWAN3

# Update list paket
opkg update

# Install MWAN3 + Luci nya
opkg install mwan3 luci-app-mwan3

# Biar nama tetap GeeLas
uci set system.@system[0].hostname='GeeLas'
uci commit system

exit 0
